### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kangddong** [doyeonjeong/Tublock#60]
# 메인 페이지

## Youtube를 Block 할 시간 설정하는 화면
- [ ] 유저가 Block한 시간을 보여주는 기능
- [ ] Block 시간을 선택하는 기능

## 알림 메세지를 설정하는 화면
- [ ] 유저가 받고싶은 알림 메세지를 작성하는 기능
- [ ] 작성한 메세지를 Preview 하는 기능

## Push 기능

# 설정 페이지
- [ ] App Version 표시 기능
- [ ] 개인정보 처리방침 페이지
- [ ] 알림 설정
- [ ] 스크린 타임 권한 설정

## 화면 구조
```
├─ Tublock
│   └─ Tublock
│       ├─ Sources
│          ├─ MainScene
│            └── SetMaximum
│            └── SetMessage
└── Project Environment.md
```

**Comment by gaeng2y** [comment]
스크린 타임 관련해서 권한 얻는 거부터 시작해야겠네요!
